### ISSUE TITLE
comment on module loading in nameko.cli.run

### ISSUE THREAD

**Issue by kollhof** [onefinestay/nameko#221]
If I read this correctly, https://github.com/onefinestay/nameko/blob/2.0/nameko/cli/run.py#L53 asks if there is another way to distinguish between not finding a module and finding a module but having an exception during loading of that module.

You could use https://docs.python.org/2/library/imp.html to first find the module using https://docs.python.org/2/library/imp.html#imp.find_module
If found you can then load it using https://docs.python.org/2/library/imp.html#imp.load_module
In Python 3 you probably want to use https://docs.python.org/3/library/importlib.html#module-importlib

**Comment by etataurov** [comment]
Yes, this will be great,
but...
for python 2 we need a lot of code, because we need to aquire import lock, call find_module for each submodule in 'module1.module2.module3'
for python 3 imp is deprecated, and the best choice is to use importlib's find_spec and then load_module, but importlib module has changed between 3.3 and 3.4 (new methods was added, some became deprecated).
So if implement this then there will be deprecated code or a lot of code to handle different import libraries for different python version.
IMHO current solution is hackish, but works and doesn't require a lot of code. so it's more robust

**Comment by rochacbruno** [comment]
what about werkzeug.utils.import_string?

**Comment by mattbennett** [comment]
@rochacbruno, `werkzeug.utils.import_string` looks ideal

**Comment by davidszotten** [comment]
from what i can see, `import_string` doesn't help distinguishing missing modules from existing modules with bad imports

**Comment by mattbennett** [comment]
@davidszotten it does:

``` python
# invalid.py
class Foo():
    name = "".join()
```

``` pycon
>>> import_string('invalid.Foo')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    import_string('invalid.Foo')
  File "/Users/mattbennett/.virtualenvs/tmp-7400bce6a277ba7b/lib/python2.7/site-
packages/werkzeug/utils.py", line 418, in import_string
    __import__(import_name)
  File "invalid.py", line 1, in <module>
    class Foo():
  File "invalid.py", line 2, in Foo
    name = "".join()
TypeError: join() takes exactly one argument (0 given)
```

**Comment by mattbennett** [comment]
Ah, I had misremembered what the problem was here. Sadly, `werkzeug.utils.import_string` doesn't help. You still just get an `ImportError`.
