### ISSUE TITLE
Scrapy Script inside Container ends up with Issues

### ISSUE THREAD

**Issue by kgrvamsi** [onefinestay/nameko#347]
I'm trying to run the Scrapy API crawler class inside the nameko container either by @time or @consume but the behaviour is that first time the scrapy crawler service executes fine but the next time it ends up with the following issues

```
error handling worker <WorkerContext [watchmen.random_checking] at 0x7f9e1518c1d0>: 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nameko/containers.py", line 414, in _run_worker
    result = method(*worker_ctx.args, **worker_ctx.kwargs)
  File "./updater.py", line 73, in random_checking
    reactor.run()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1193, in run
    self.startRunning(installSignalHandlers=installSignalHandlers)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1173, in startRunning
    ReactorBase.startRunning(self)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 684, in startRunning
    raise error.ReactorNotRestartable()
ReactorNotRestartable
```
code

```
# these are the Scrapy and Twisted Framework Decorators used
@defer.inlineCallbacks
def crawl(runner):
    yield runner.crawl(RandomSpider)
    #reactor.stop()

class WatchmenService(object):
    name = 'watchmen'

    @consume(queue=ew_pdf_queue)
    def random_checking(self, msg):
        runner = CrawlerRunner(get_project_settings())
        crawl(runner)
        reactor.run()
```
@davidszotten can you please help.

**Comment by mattbennett** [comment]
Nameko uses eventlet for [concurrency](http://nameko.readthedocs.io/en/stable/key_concepts.html?highlight=concurrency#concurrency). Scrapy uses Twisted, and the two unfortunately cannot be used together. This is an inherent incompatibility between the two event loops.
